version: '3.8'
services:
  prattle-backend:
    build:
      context: ./server
      dockerfile: DockerFile
    image: naveenmraja/prattle-backend:1.1
    container_name: prattle-backend
    env_file:
      - ./.env.backend
  nginx :
    build :
      context: .
      dockerfile: ./nginx/DockerFile
      args:
        - REACT_APP_GOOGLE_SITE_KEY=$REACT_APP_GOOGLE_SITE_KEY
    image: naveenmraja/prattle-nginx:1.2
    container_name: nginx
    ports :
      - "80:80"
    depends_on:
      - prattle-backend
    links:
      - prattle-backend